// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9SGQfiTQ9FLVMnr3C4_kSMVzu-nnB8Q',
    appId: '1:828143423734:web:8a528f36866b11cb9cdcd7',
    messagingSenderId: '828143423734',
    projectId: 'onyx-cinema',
    authDomain: 'onyx-cinema.firebaseapp.com',
    storageBucket: 'onyx-cinema.appspot.com',
    measurementId: 'G-V0NP9WR3FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4EWkkhdtLt_19L8wI99wkln7k2qBPt8',
    appId: '1:828143423734:android:f720484ddf56146d9cdcd7',
    messagingSenderId: '828143423734',
    projectId: 'onyx-cinema',
    storageBucket: 'onyx-cinema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEHyx5l6O8daQ8TNZdKPrMcWKYksDaNI',
    appId: '1:828143423734:ios:9bccb99c6d4d33589cdcd7',
    messagingSenderId: '828143423734',
    projectId: 'onyx-cinema',
    storageBucket: 'onyx-cinema.appspot.com',
    iosBundleId: 'com.example.onyxCinemaTicketBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEHyx5l6O8daQ8TNZdKPrMcWKYksDaNI',
    appId: '1:828143423734:ios:7a52394678b876999cdcd7',
    messagingSenderId: '828143423734',
    projectId: 'onyx-cinema',
    storageBucket: 'onyx-cinema.appspot.com',
    iosBundleId: 'com.example.onyxCinemaTicketBooking.RunnerTests',
  );
}
